[project]
authors = ["Dmitri Moscoglo <dmmoskoglo@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "mojo_src"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.5.0,<25"
scikit-learn = ">=1.5.2,<2"
pandas = ">=2.2.3,<3"
pytorch = ">=2.5.1,<3"
numpy = ">=1.26.4,<2"
torchvision = ">=0.20.1,<0.21"
